# Generated by Django 4.1.4 on 2023-05-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='decription',
            new_name='description',
        ),
    ]
